### ISSUE TITLE
custom-action-telegram fix

### ISSUE THREAD

**Issue by IncubusRK** [BFastovetskiy/itop#1]
custom-action-telegram won't send anything. And result is empty string.
Curl option CURLOPT_FOLLOWLOCATION => true is required to follow api redirects

**Comment by BFastovetskiy** [comment]
Good day.

Give an example when you want to use this parameter. According to the API Telegram Bots documentation, the answer is always a JSON object.

Forwarding in the answer is not returned.

**Comment by IncubusRK** [comment]
In my default installation 
 curl http://api.telegram.org/bot[ID]/getUpdates
Return: 301 Moved Permanently
And  curl -L http://api.telegram.org/bot[ID]/getUpdates
Correctly return bot messages

**Comment by BFastovetskiy** [comment]
The module does not use the method GetUpdates.
If you make your module based on mine, then change it in your own.

**Comment by IncubusRK** [comment]
It's just example, sendMessage also won't work
